### ISSUE TITLE
Error installing in windows

### ISSUE THREAD

**Issue by antoniovazquezblanco** [DarkSector/python-particle#7]
As far as I can see, the package uses pexpect that is a UNIX only package.

I would love to be able to use this package in windows if possible and if not, installation in this platform should be restricted.

Thank you!

```
>pip install python-particle
Defaulting to user installation because normal site-packages is not writeable
Collecting python-particle
  Using cached python-particle-0.2.zip (5.9 kB)
Collecting python-dateutil==2.4.2
  Using cached python_dateutil-2.4.2-py2.py3-none-any.whl (188 kB)
Collecting pytz==2015.4
  Using cached pytz-2015.4-py2.py3-none-any.whl (475 kB)
Collecting requests==2.7.0
  Using cached requests-2.7.0-py2.py3-none-any.whl (470 kB)
Collecting pexpect==3.3
  Using cached pexpect-3.3.tar.gz (132 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files\python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Anton\\AppData\\Local\\Temp\\pip-install-o88vl1ph\\pexpect\\setup.py'"'"'; __file__='"'"'C:\\Users\\Anton\\AppData\\Local\\Temp\\pip-install-o88vl1ph\\pexpect\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Anton\AppData\Local\Temp\pip-pip-egg-info-58r1bghw'
         cwd: C:\Users\Anton\AppData\Local\Temp\pip-install-o88vl1ph\pexpect\
    Complete output (17 lines):
    Traceback (most recent call last):
      File "C:\Users\Anton\AppData\Local\Temp\pip-install-o88vl1ph\pexpect\pexpect\__init__.py", line 73, in <module>
        import resource
    ModuleNotFoundError: No module named 'resource'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Anton\AppData\Local\Temp\pip-install-o88vl1ph\pexpect\setup.py", line 3, in <module>
        from pexpect import __version__
      File "C:\Users\Anton\AppData\Local\Temp\pip-install-o88vl1ph\pexpect\pexpect\__init__.py", line 86, in <module>
        raise ImportError(str(err) + '''
    ImportError: No module named 'resource'

    A critical module was not found. Probably this operating system does not
    support it. Pexpect is intended for UNIX-like operating systems.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by DarkSector** [comment]
This package is kinda old. I don't know if it works right now given the API changes in the particle toolchain. That being said, I am happy to accept PRs to exclude no supported platforms
